# Generated by Django 6.0.3 on 2026-03-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Who am I?', max_length=200)),
                ('bio_intro', models.TextField(blank=True, help_text='The first introductory paragraph for the about me section.')),
                ('bio_details', models.TextField(blank=True, help_text='The main details to go after the intro.')),
                ('cv_file', models.FileField(blank=True, help_text='Upload your Resume/CV here', null=True, upload_to='cv/')),
            ],
        ),
    ]
