# Generated by Django 6.0.3 on 2026-03-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload your profile picture here', null=True, upload_to='profile/'),
        ),
    ]
